<a href="https://colab.research.google.com/github/AhmedNasserEnna/AhmedNasserEnna/blob/main/Pytorch_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
tensor = torch.arange(10)

In [4]:
tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Reshape and view
tensor = tensor.reshape(2,5)
tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
# reshape using -1
tensor2= torch.arange(10)
tensor2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
tensor2=tensor2.reshape(2,-1)
tensor2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
tensor3= torch.arange(10)
tensor3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
tensor3=tensor3.reshape(-1,5)
tensor3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [16]:
tensor4= torch.arange(10)
tensor4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
tensor4= tensor4.view(2,5)
tensor4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
# update
tensor5 =torch.arange(10)
tensor5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
tensor6 = tensor5.reshape(2,5)
tensor6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [22]:
tensor5[1]=4141
tensor5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [23]:
tensor6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [27]:
#Slicing
tensor7 = tensor5.reshape(5,2)
tensor7

tensor([[   0, 4141],
        [   2,    3],
        [   4,    5],
        [   6,    7],
        [   8,    9]])

In [28]:
tensor5[1]

tensor(4141)

In [32]:
tensor8 = tensor7[:,1]
tensor8

tensor([4141,    3,    5,    7,    9])

In [33]:
tensor9 = tensor7[:,1:]
tensor9

tensor([[4141],
        [   3],
        [   5],
        [   7],
        [   9]])

In [35]:
tensor8 = tensor7[:,0]
tensor8

tensor([0, 2, 4, 6, 8])

In [36]:
tensor9 = tensor7[:,0:]
tensor9

tensor([[   0, 4141],
        [   2,    3],
        [   4,    5],
        [   6,    7],
        [   8,    9]])